name: Create Release

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  content: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build-and-release:
    name: Build and Release
    runs-on: ubuntu-latest
    permissions:
      contents: write # Required to create a release

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up pnpm
        uses: pnpm/action-setup@v4
        # The action will automatically use the pnpm version from package.json's 'packageManager' field

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build project
        run: pnpm run build
        env:
          # VITE_BASE_URL is set in vite.config.js, no need to override here unless dynamic
          CI: true

      - name: Create a ZIP archive of the dist folder
        run: |
          zip -r dist.zip ./dist

      - name: Create Release Tag
        id: tag
        run: echo "TAG_NAME=release-$(date +'%Y-%m-%d-%H%M%S')" >> $GITHUB_ENV

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.TAG_NAME }}
          name: "Release ${{ env.TAG_NAME }}"
          body: "Automated release of build artifacts from the main branch."
          draft: false
          prerelease: false
          files: |
            dist.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
